FROM tensorflow/serving

ENV KMP_AFFINITY=noverbose
ENV TF_CPP_MIN_LOG_LEVEL=3

WORKDIR /models
COPY ./sqli_model /models/sqli_model
COPY ./models.config /models/models.config

EXPOSE 8500
EXPOSE 8501

CMD ["--model_config_file=/models/models.config"]
